### ISSUE TITLE
エラーが発生して処理できないファイルがある

### ISSUE THREAD

**Issue by akm** [akm/object_pascal_analyzer#6]
```
$ exe/object_pascal_analyzer csv spec/jedi-jvcl/tests/restructured/examples > /dev/null
Traceback (most recent call last):
	15: from exe/object_pascal_analyzer:5:in `<main>'
	14: from /Users/takeshi/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	13: from /Users/takeshi/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	12: from /Users/takeshi/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	11: from /Users/takeshi/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	10: from /Users/takeshi/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/object_pascal_analyzer-0.1.0/lib/object_pascal_analyzer/cli.rb:24:in `csv'
	 9: from /Users/takeshi/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/object_pascal_analyzer-0.1.0/lib/object_pascal_analyzer.rb:11:in `load'
	 8: from /Users/takeshi/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/object_pascal_analyzer-0.1.0/lib/object_pascal_analyzer.rb:11:in `with_object'
	 7: from /Users/takeshi/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/object_pascal_analyzer-0.1.0/lib/object_pascal_analyzer.rb:11:in `each'
	 6: from /Users/takeshi/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/object_pascal_analyzer-0.1.0/lib/object_pascal_analyzer.rb:13:in `block in load'
	 5: from /Users/takeshi/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/object_pascal_analyzer-0.1.0/lib/object_pascal_analyzer/pascal_file_loader.rb:23:in `execute'
	 4: from /Users/takeshi/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/object_pascal_analyzer-0.1.0/lib/object_pascal_analyzer/pascal_file_loader.rb:23:in `open'
	 3: from /Users/takeshi/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/object_pascal_analyzer-0.1.0/lib/object_pascal_analyzer/pascal_file_loader.rb:24:in `block in execute'
	 2: from /Users/takeshi/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/object_pascal_analyzer-0.1.0/lib/object_pascal_analyzer/pascal_file_loader.rb:24:in `each_line'
	 1: from /Users/takeshi/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/object_pascal_analyzer-0.1.0/lib/object_pascal_analyzer/pascal_file_loader.rb:28:in `block (2 levels) in execute'
/Users/takeshi/.anyenv/envs/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/object_pascal_analyzer-0.1.0/lib/object_pascal_analyzer/pascal_file_loader.rb:28:in `=~': invalid byte sequence in UTF-8 (ArgumentError)
```

UTF-8として扱おうとして失敗している模様。どのファイルでエラーが発生しているかは不明。

**Comment by akm** [comment]
修正を確認したのでクローズします

```
$ exe/object_pascal_analyzer csv spec/jedi-jvcl/tests/restructured/examples > /dev/null
$
```
